### ISSUE TITLE
小建议：pksj列表直接列出所有表情的id

### ISSUE THREAD

**Issue by ShizukuNia** [Agnes4m/nonebot_plugin_pjsk#10]
现在想查表情id，得先[pjsk列表]，再[pjsk列表 <角色名>]查看这个角色所有表情的 ID，感觉有点繁琐了
希望[pjsk列表]能直接列出所有角色所有表情的id

**Comment by Agnes4m** [comment]
数量有点多，100多个表情挤在一个图里，我自认为并不美观，我是参考原作者提供的dc机器人功能做的，如果需要我可以做连续对话
