### ISSUE TITLE
Assets URL return 403 status code

### ISSUE THREAD

**Issue by SkyDynamic** [Agnes4m/nonebot_plugin_pjsk#15]
插件中提供的地址为：`https://raw.gitmirror.com/TheOriginalAyaka/sekai-stickers/main/`
若使用此地址进行资源下载会导致403并且nonebot2直接退出  

使用github原地址: `https://raw.githubusercontent.com/TheOriginalAyaka/sekai-stickers/main/`
则没有任何问题  

## 这里提个建议，不要一开始就给插件写死镜像站, 可以先写原地址, 再给用户提供可选选项

**Comment by lgc2333** [comment]
地址是可以在 `env` 配置项中修改的…… 参考下面两行

https://github.com/Agnes4m/nonebot_plugin_pjsk/blob/14e50b2ca4191276de0fa8ca53ec6be55fd5330f/nonebot_plugin_pjsk/config.py#L11-L14

至于为什么一开始就写镜像站，是为国内用户考量
之后会在README中加入提示

**Comment by Agnes4m** [comment]
直接用代理ghproxy.com或者其他吧，国内外都能访问

**Comment by SkyDynamic** [comment]
好的明白了, 那这里就Close Issus咯？
