### ISSUE TITLE
在别的群看到HoshinoBot这个pjsk插件发qq群可以透明，右键存它生成的图是png格式，都是基于nonebot开发，感觉可以参考下

### ISSUE THREAD

**Issue by atriatri20** [Agnes4m/nonebot_plugin_pjsk#19]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-pjsk/assets/21164819/42647bfc-6dee-4260-8fba-0769295b8d5c)

项目地址是： https://github.com/Nao-desu/pjsk_sticker

**Comment by lgc2333** [comment]
related with #17 

我的 `nonebot-plugin-pjsk` 没有问题，可以确定 99% 不是插件的锅
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-pjsk/assets/59048777/6697f6f2-7ee7-4464-adf3-6a573fb19a44)
