### ISSUE TITLE
获取资源时因不支持的参数报错

### ISSUE THREAD

**Issue by TheValkyrja** [Agnes4m/nonebot_plugin_pjsk#23]
httpx == 0.28.0的情况下，插件尝试获取资源时提示存在已被弃用的proxies参数。

![image](https://github.com/user-attachments/assets/23ddb537-2002-4861-9e1a-48cd516197fd)

**Comment by lgc2333** [comment]
目前nonebot的httpx驱动器暂未支持httpx 0.28，请等待发版，此问题马上修复

**Comment by TheValkyrja** [comment]
> 目前nonebot的httpx驱动器暂未支持httpx 0.28，请等待发版，此问题马上修复

已经通过回退0.27.2恢复正常使用，感谢回复。
