### ISSUE TITLE
OSError: cannot open resource

### ISSUE THREAD

**Issue by Fsyxr** [Agnes4m/nonebot_plugin_pjsk#4]
![image](https://github.com/Agnes4m/nonebot_plugin_pjsk/assets/85301551/f4efc7ae-5c64-4ef9-aa2d-7f7922df64d7)
![image](https://github.com/Agnes4m/nonebot_plugin_pjsk/assets/85301551/b080bbae-0c83-4b0c-8f8d-117e320ab957)
资源路径没问题啊

**Comment by Fsyxr** [comment]
好像是字体有问题?

**Comment by ghost** [comment]
是字体问题，把字体文件也放到data/pjsk下面

**Comment by Agnes4m** [comment]
已更新新版本，支持读取电脑的字体了
现在的路径是`data/pjsk/resource/{}/{}`
字体的路径是`data/pjsk/resource/ShangShouFangTangTi.ttf`

字体如果不存在会尝试从电脑内置字体中获取

**Comment by Fsyxr** [comment]
![image](https://github.com/Agnes4m/nonebot_plugin_pjsk/assets/85301551/9810b70a-4ab5-4ad4-97dd-e44630fce223)
这读的怎么是那个测试图,固定的还不会改成别的角色的

**Comment by Agnes4m** [comment]
请更新新版本

**Comment by Agnes4m** [comment]
查看文档更新v0.1.0，文件路径改变了同时支持加载自动下载，如果需要清理内存请删除原data/pjsk下内容，第一次启动会自动下载，第二次启动正式可以使用
