### ISSUE TITLE
许愿：希望以后可以指定表情包进行制作

### ISSUE THREAD

**Issue by ghost** [Agnes4m/nonebot_plugin_pjsk#5]
许愿：希望以后可以指定表情包进行制作
![emutest](https://github.com/Agnes4m/nonebot_plugin_pjsk/assets/118903437/3921ca36-b9a6-4095-8d32-3580af26f268)

**Comment by Agnes4m** [comment]
一开始是想这么做的，主要我没玩过pjsk，不知道人名对应的）应援色我直接对着发色来的））））））

**Comment by Satori3rdEye** [comment]
> 一开始是想这么做的，主要我没玩过pjsk，不知道人名对应的）应援色我直接对着发色来的））））））

颜色的话也可参考这里https://st.ayaka.one/

**Comment by Agnes4m** [comment]
> > 一开始是想这么做的，主要我没玩过pjsk，不知道人名对应的）应援色我直接对着发色来的））））））
> 
> 颜色的话也可参考这里https://st.ayaka.one/

我就是从这里找的灵感去做的，但是每个人都设置一个rgb颜色好麻烦，偷个懒用内置颜色看看差不多就用了）

**Comment by Agnes4m** [comment]
已完成
