### ISSUE TITLE
想问下插件加载失败是什么原因

### ISSUE THREAD

**Issue by RainbowDashKira** [Agnes4m/nonebot_plugin_pjsk#6]
![}0LI`FBD95 {7IGG7T`B(Q3](https://github.com/Agnes4m/nonebot_plugin_pjsk/assets/117131527/cc6ff88d-a2c1-4af1-9570-e2851a2f2483)
第一次加载提示没有aio驱动器 我去装了一个，然后就是这个报错了。

**Comment by Agnes4m** [comment]
已修复，更新v0.1.0
